# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
    exclude: "{{cookiecutter.project_slug}}"
  - id: check-json
    exclude: "{{cookiecutter.project_slug}}"
  - id: check-toml
    exclude: "{{cookiecutter.project_slug}}"
  - id: check-docstring-first
  - id: check-case-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: debug-statements
  - id: forbid-submodules

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.6
  hooks:
    - id: ruff
      exclude: "{{cookiecutter.project_slug}}"
      args: ['--fix']
    - id: ruff-format
      exclude: "{{cookiecutter.project_slug}}"

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.18  # Use the ref you want to point at
  hooks:
  - id: mdformat
    # Optionally add plugins
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.4.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
