# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-docstring-first
  - id: check-case-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: forbid-submodules

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.6
  hooks:
    - id: ruff
      args: ['--fix']
    - id: ruff-format
