# Test workflow for the cookiecutter template.

name: Python package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.10", "3.11", "3.12" ]

    steps:
    - uses: actions/checkout@v4
    - uses: excitedleigh/setup-nox@v2.1.0

      name: ${{ matrix.python }}
    - run: nox -s test -p ${{ matrix.python }}
