# Test workflow for the cookiecutter template.

name: Python package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: excitedleigh/setup-nox@v2.1.0
    - run: nox -s test
